title: Drei's Blog
description: My Computer Science Journey

url: "astoyanow.github.io/"
baseurl: "/mysite"
paginate_path: "/page:num/"
permalink: /:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index
  - title: About
    url: /about
  - title: Contact
    url: /contact
  #- title: Projects
  #  url: /projects

social:
  github: astoyanow
  twitter: _stoyahknow
  facebook:
  email: astoyanow13@gmail.com

google_analytics: "UA-58263416-1"
