title: Drei's Blog
description: My Computer Science Journey

url: http://github.com/astoyanow/csci340blog
baseurl: "/Users/Andrei/Documents/GitHub/csci340blog"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: astoyanow
  twitter: _stoyahknow
  facebook:
  email: astoyanow13@gmail.com

google_analytics: "UA-58263416-1"
